// !! Auto-generated by scripts/generate-cms-types.js
// !! Run: pnpm cms:types
// !! Source: apps/cms/types/generated/contentTypes.d.ts

// ─── Media (plugin::upload.file)

export interface StrapiImageFormat {
  url: string
  width: number
  height: number
  name: string
  hash: string
  ext: string
  mime: string
  size: number
}

export interface StrapiMedia {
  id: number
  documentId: string
  name: string
  alternativeText: string | null
  caption: string | null
  width: number | null
  height: number | null
  formats: {
    thumbnail?: StrapiImageFormat
    small?: StrapiImageFormat
    medium?: StrapiImageFormat
    large?: StrapiImageFormat
  } | null
  hash: string
  ext: string
  mime: string
  size: number
  url: string
  previewUrl: string | null
  provider: string
  provider_metadata: unknown
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

// ─── Components

export interface JoyeriaOro {
  id: number
  Tipo: 'italiano' | 'nacional' | 'importado' | null
  Kilates: number | null
  Color: 'amarillo' | 'blanco' | 'rosa' | null
  PesoGramos: string | null
}

export interface JoyeriaMedidas {
  id: number
  Tipo: 'cadena' | 'anillo' | 'arete' | 'dije' | null
  LargoCm: string | null
  DiametroMm: string | null
}

export interface ComponentesEnlace {
  id: number
  Url: string
  AbrirEnNuevaPestana: boolean
}

export interface ComponentesMarca {
  id: number
  Imagotipo: StrapiMedia
  Isotipo: StrapiMedia
}

export interface ComponentesMetadatos {
  id: number
  TituloCorto: string
  TituloLargo: string
  Descripcion: string
}

export interface ComponentesCarruselDeBanner {
  id: number
  Imagen: StrapiMedia
  Enlace: ComponentesEnlace | null
}

// ─── Response wrappers

export interface StrapiPagination {
  page: number
  pageSize: number
  pageCount: number
  total: number
}

export interface StrapiListResponse<T> {
  data: T[]
  meta: { pagination: StrapiPagination }
}

export interface StrapiSingleResponse<T> {
  data: T
  meta: Record<string, never>
}

// ─── Content types
// api::categoria.categoria
export interface Categoria {
  id: number
  documentId: string
  Label: string | null
  Producto: Producto | null
  Slug: string | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

// api::global.global
export interface Global {
  id: number
  documentId: string
  AnnouncementBar: string | null
  CarruselBanner: ComponentesCarruselDeBanner[] | null
  Marca: ComponentesMarca | null
  Metadatos: ComponentesMetadatos | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

// api::producto.producto
export interface Producto {
  id: number
  documentId: string
  Activo: boolean | null
  Categorias: Categoria[] | null
  Descripcion: string | null
  DescripcionCorta: string | null
  Descuento: string | null
  Imagenes: StrapiMedia[] | null
  Medidas: JoyeriaMedidas | null
  Oro: JoyeriaOro | null
  Precio: string | null
  Slug: string | null
  Stock: number | null
  Tags: unknown | null
  Titulo: string | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}
